version: '3'

services:
  mcp-service:
    build: .
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./output:/app/output
      - ./ts_files:/app/ts_files
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      # 可以添加其他环境变量
      # - API_KEY=your-api-key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 